# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculate the maximum module length of each column in the matrix
#' @description Calculate the maximum module length of each column in the matrix
#' @param x a matrix
#' @return a constant of maximum module length of each column in the matrix
#' @examples
#' \dontrun{
#' mu <- c(10,10)
#' s <- matrix(c(1,2,2,1,1,3,4,5,6,7,8,9), nrow = 2, ncol = 6)
#' n <- maxcol(s)
#' n
#' }
#' @export
maxcol <- function(x) {
    .Call('_SA23204156_maxcol', PACKAGE = 'SA23204156', x)
}

